stages:
  - test
  - build

pytest:
  stage: test
  image: python:2.7.12-slim
  cache:
    paths:
      - pip-cache
  before_script:
    - ci-scripts/before.sh
  variables:
    COVERAGE_FILE: .coverage
    PIP_CACHE_DIR: pip-cache
    ONE_AUTH: "/tmp/test-one-auth"
    ONE_XMLRPC: "http://localhost:2633/RPC2"
  script:
    -  python setup.py test
  tags:
    - docker
    - docker-build

build_image:
  stage: build
  image: docker:git
  variables:
    GODEBUG: 'netdns=cgo'
  script:
    - ci-scripts/build-image.sh
  tags:
    - docker
    - docker-build
