version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.2
    restart: always
    ports:
      - "${ETCD_PORT}:${ETCD_PORT}"
    volumes:
      - "/tmp/data:/data"
    command: --listen-client-urls http://0.0.0.0:${ETCD_PORT} --advertise-client-urls http://0.0.0.0:${ETCD_PORT} --data-dir /data

  skydns:
    image: skynetservices/skydns:2.5.3a
    restart: always
    ports:
      - "${DNS_PORT}:${DNS_PORT}"
      - "${DNS_PORT}:${DNS_PORT}/udp"
    links:
      - etcd
    depends_on:
      - etcd
    command: -machines http://etcd:${ETCD_PORT} -addr 0.0.0.0:${DNS_PORT} -no-rec
